---
title: "book-codes"
author: "nr"
date: "4 7 2022"
output: html_document
---

```{r}
library(rethinking)
library(animation)
```

# Chapter 4 - Linear models

```{r}
# 4.7
data(Howell1)
d <- Howell1
# 4.10
d2 <- d[d$age >= 18,]
# r code 4.11 and 12
curve(dnorm(x, 178, 20), from = 100, to=250)
curve(dnorm(x, 0, 50), from = -10, to=60)

# r code 4.13
sample_mu <- rnorm(1e4, 178, 20)
sample_sigma <- runif(1e4, 0, 50)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
density(prior_h)

# r code 4.14
mu.list <- seq(from=140, to=160, length.out = 200)
sigma.list <- seq(from=4, to=9, length.out=200)
post <- expand.grid(mu = mu.list, sigma=sigma.list)
post$LL <- sapply(1:nrow(post), function(i) sum( dnorm(
  d2$height, 
  mean = post$mu[i],
  sd = post$sigma[i],
  log = TRUE )))
post$prod <- post$LL + dnorm (post$mu, 178, 20, TRUE) + dunif( post$sigma, 0, 50, TRUE)
post$prob <- exp(post$prod - max(post$prod))

# r code 4.15
contour_xyz(post$mu, post$sigma, post$prob)
image_xyz(post$mu, post$sigma, post$prob)
```

### sampling from the posterior

```{r}
# r code 4.17
sample.rows <- sample(1:nrow(post), size=1e4, replace = TRUE, prob = post$prob) # returns the index of rows
sample.mu <- post$mu[sample.rows]
sample.sigma <- post$sigma[sample.rows]

plot(sample.mu, sample.sigma, cex=0.5, pch=16, col=col.alpha(rangi2, 0.1))

# r code 4.19
dens(sample.mu)
dens(sample.sigma)

# r doce 4.20
HPDI(sample.mu)
HPDI(sample.sigma)
```

### for case when posterior is not always so Gaussian in shape

```{r}
d3 <- sample(d2$height, size = 20)
# r doce 4.22
mu.list <- seq(from=150, to=170, length.out = 200)
sigma.list <- seq(from=4, to=20, length.out=200)
post2 <- expand.grid(mu = mu.list, sigma=sigma.list)
post2$LL <- sapply(1:nrow(post), function(i)
    sum( dnorm( d3, mean = post2$mu[i], sd = post2$sigma[i],log = TRUE ))
  )
post2$prod <- post2$LL + dnorm (post2$mu, 178, 20, TRUE) + dunif( post2$sigma, 0, 50, TRUE)
post$prob <- exp(post2$prod - max(post2$prod))

sample2.rows <- sample(1:nrow(post2), size=1e4, replace = TRUE, prob = post2$prob) # returns the index of rows
sample2.mu <- post2$mu[sample2.rows]
sample2.sigma <- post2$sigma[sample2.rows]

plot(sample2.mu, sample2.sigma, cex=0.5, col=col.alpha(rangi2, 0.1), 
     xlab='mu', ylab='sigma', pch = 16)

dens(sample2.sigma, norm.comp = TRUE)
```

### 4.3.5 Fitting the model with map

```{r}
library(rethinking)
data("Howell1")
d <- Howell1

d2 <- d[d$age >= 18, ]

flist <- alist(
  height ~ dnorm(mu, sigma),
  mu ~ dnorm(156, 10),
  sigma ~ dunif(0, 50)
)

m4.1 <- map( flist, data = d2)
precis(m4.1)
```

```{r}
# r code 4.19

m4.2 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu ~ dnorm(178, 0.1),
    sigma ~ dunif(0, 50)
  ), 
  data = d2
)
precis(m4.2)
```

# 4.4 Addign a predictor

```{r}
plot(d2$height ~ d2$weight)

```

